/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#120d0c',
        'surface-container-low': '#201a19',
        'surface-container': '#241e1d',
        'surface-container-high': '#2f2928',
        'surface-container-highest': '#3a3332',
        'surface-dim': '#171211',
        'surface-bright': '#3e3837',
        'surface-variant': '#3a3332',
        'on-surface': '#ece0de',
        'on-surface-variant': '#d7c2bf',
        'outline': '#9f8d8a',
        'outline-variant': '#524341',
        'primary': '#ffd3cd',
        'primary-container': '#f6b0a6',
        'on-primary': '#4f231d',
        'on-primary-container': '#74413a',
        'primary-fixed': '#ffdad5',
        'primary-fixed-dim': '#fcb5ab',
        'inverse-primary': '#865048',
        'secondary': '#c6c6c7',
        'secondary-container': '#454747',
        'on-secondary': '#2f3131',
        'on-secondary-container': '#b4b5b5',
        'tertiary': '#b0e8d7',
        'tertiary-container': '#95ccbb',
        'on-tertiary': '#00382d',
        'on-tertiary-container': '#21584a',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'background': '#171211',
        'on-background': '#ece0de',
        'inverse-surface': '#ece0de',
        'inverse-on-surface': '#352f2e',
        'surface-tint': '#fcb5ab',
        'brand': '#733934',
        'gold': '#b99c7c',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '14px', fontWeight: '500', letterSpacing: '0.04em' }],
        'label-md': ['14px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.02em' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600', letterSpacing: '-0.01em' }],
        'headline-xl': ['40px', { lineHeight: '48px', fontWeight: '700', letterSpacing: '-0.02em' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '20px',
        'container-margin': '40px',
      },
    },
  },
  plugins: [],
}
